name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

#The following will check out our repo
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org0bd0bd3e.crm4.dynamics.com' #Put in URL for Dev environment
        user-name: 'admin@CRM564374.onmicrosoft.com' #Login to use this
        password-secret: ${{ secrets.password }} #Have to set up a password

#This is where the solution will be exported
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org0bd0bd3e.crm4.dynamics.com'
        user-name: 'admin@CRM564374.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: ALMTest
        solution-output-file: out/exported/ALMLab.zip

#Unpack the solution and unzip it
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/ALMLab.zip
        solution-folder: out/solutions/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true

#Then we will create a branch so we can later make a pull request
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
